### ISSUE TITLE
Bundling on Linux doesn't work?

### ISSUE THREAD

**Issue by subsoap** [GameAnalytics/GA-SDK-DEFOLD#3]
I can bundle a Linux target on Windows 10 but not Linux.

https://forum.defold.com/t/defold-integration-for-gameanalytics-def-3024/10417/26?u=pkeod

Attached zip sample of errors when building for Linux on a Linux VM (Linux Mint)

I don't know why it would make a difference but apparently it does.

[errors.zip](https://github.com/GameAnalytics/GA-SDK-DEFOLD/files/2897841/errors.zip)

**Comment by the1schwartz** [comment]
This should be fixed now in the latest version (v2.1.2)

**Comment by subsoap** [comment]
Just tested downloading fresh release on Linux Mint VM and building there. But still getting same issue.

I deleted everything and tried to download everything cleanly again just to be sure.

[errors.txt](https://github.com/GameAnalytics/GA-SDK-DEFOLD/files/2905722/errors.txt)

**Comment by the1schwartz** [comment]
Ah sorry forgot to update our release script which used the clang compiled library so the old library was used. The new one is using gcc to compile the linux lib which should fix the errors. Let me know if it still doesn't work. It is in version v2.1.3.

**Comment by subsoap** [comment]
It works now! Thank you!
